project_id = "pcmszqqklkolvvlabohq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
port = 54326
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_refresh_token_reuse_interval = 10
enable_signup = true

[rest]
enabled = true
port = 54327

[realtime]
enabled = true
port = 54328

[functions.admin-update-user]
verify_jwt = true

[functions.send-email-notification]
verify_jwt = true

[functions.send-work-assignment-notification]
verify_jwt = false

[functions.notify-manager-ticket-closed]
verify_jwt = true

[functions.create-housekeeper]
verify_jwt = true

[functions.send-assignment-notification]
verify_jwt = true

[functions.send-task-notification]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-otp-password-reset]
verify_jwt = false

[functions.verify-otp-reset-password]
verify_jwt = false

[functions.send-sms-otp]
verify_jwt = false

[functions.generate-login-link]
verify_jwt = false

[functions.previo-sync-rooms]
verify_jwt = true

[functions.previo-sync-reservations]
verify_jwt = true

[functions.previo-update-room-status]
verify_jwt = true

[functions.previo-update-minibar]
verify_jwt = true

[functions.manager-reset-password]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true
